<?php
/**
 * Created by PhpStorm.
 * User: DTSHOME
 * Date: 27/2/2019
 * Time: 21:29 ч.
 */

namespace backend\controllers;


use backend\models\UserForm;
use yii\base\Controller;
use Yii;
use yii\web\Response;

class ApiController extends Controller
{

    public function actions()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return parent::actions(); // TODO: Change the autogenerated stub
    }

    public function actionCreateUser(){
        $model = new UserForm();
        $require = json_decode(Yii::$app->request->getRawBody(),true);
        $model->setAttributes($require);
        if($model->validate()) {
            return $model->createNewUser();
        } else {
            return $model;
        }
    }
}