<?php

namespace backend\controllers;

use backend\models\LanguageForm;
use backend\models\LanguageSearch;
use denchotsanov\rbac\filter\AccessControl;
use Yii;
use yii\filters\VerbFilter;

class TranslateController extends MainController
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    '*'=> ['GET','POST'],
                ],
            ],
        ];
    }
    public function beforeAction($action)
    {
        $this->view->title = Yii::t('admin','Translate');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        $searchModel = new LanguageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionNewLanguage(){
        $model = new LanguageForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }
        return $this->renderAjax('newLanguage',['model'=>$model]);

    }
}