<?php

namespace backend\controllers;

use backend\models\UserForm;
use backend\models\UserStatusUpdate;
use denchotsanov\rbac\filter\AccessControl;
use denchotsanov\rbac\models\AssignmentModel;
use Yii;
use backend\models\User;
use backend\models\UserSearch;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;


/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends MainController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    '*'=> ['GET','POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $modelAssigment = $this->findAssigment($id);
        $userModel= [
            'id' => $model->id,
            'username' => $model->username,
            'email'=> $model->email,
            'avatar' => $model->getUserAvatarUrl(),
            'name' => $model->getProfile(),
            'blockedUser' => ($model->status === User::STATUS_BANED || $model->status === User::STATUS_LOCKED),

        ];
        return $this->render('view', [
            'model' =>$model,
            'modelAssigment'=> $modelAssigment,
            'user' =>$userModel,
        ]);
    }

    /**
     *
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new UserForm();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->renderAjax('create',['model'=>$model]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionStatusUpdate(){

        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = new UserStatusUpdate();
        $require = json_decode(Yii::$app->request->getRawBody(),true);
        $model->load($require);
        if ($model->update()){
            return ['seccess'=>'OK'];
        } else {
            return ['seccess'=>'NOK'];
        }

    }

    public function actionCreateUser(){
        $model = new UserForm();
        $require = json_decode(Yii::$app->request->getRawBody(),true);
        $model->setAttributes($require);
        if($model->validate()) {
            return $model->createNewUser();
        } else {
            return $model;
        }
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }

    public function findAssigment($id){
        $userClass = Yii::$app->user->identityClass;
        if (($userModel = $userClass::findIdentity($id)) !== null) {
            return new AssignmentModel($userModel);
        }

        throw new NotFoundHttpException(Yii::t('admin', 'The requested page does not exist.'));
    }
}
